ICON = "src/assets/icon.png"
CROSS = "src/assets/cross.png"
CIRCLE = "src/assets/circle.png"
DRAW = "src/assets/draw.png"
GRID = "src/assets/grid.png"
HUGGING = "src/assets/hugging.png"
CLICK = "src/assets/click.wav"
BACKGROUNDS_FOLDER = "src/assets/backgrounds/"
