ICON = "src/img/icon.png"
CROSS = "src/img/cross.png"
CIRCLE = "src/img/circle.png"
DRAW = "src/img/draw.png"
GRID = "src/img/grid.png"
HUGGING = "src/img/hugging.png"
BACKGROUNDS_FOLDER = "src/img/backgrounds/"
