AI_GAME = "Играть с компьютером"
HUMAN_GAME = "Играть с другом"
AI_NAME = "Sanakan"
FIRST_PLAYER_NAME = "Нагибатор228"
SECOND_PLAYER_NAME = "Дед инсайд"
DRAW = "Ничья!"
VIEW_RESULT = "Посмотреть результат"
PLAY_AGAIN = "Играть снова"
